kure-kosen/cho_kure_web

app/controllers/admin/events_controller.rb
app/helpers/admin/events_helper.rb
app/models/event.rb
app/views/admin/events/_form.html.erb
app/views/admin/events/edit.html.erb
app/views/admin/events/index.html.erb
app/views/admin/events/new.html.erb
app/views/admin/events/show.html.erb
app/views/layouts/admin.html.erb
config/application.rb
config/initializers/time_formats.rb
config/locales/models/event.ja.yml
config/routes.rb
db/fixtures/30_event.rb
db/migrate/20171114162603_create_events.rb
db/schema.rb
spec/factories/events.rb
spec/models/event_spec.rb

closed #11 
Datetimeの表示が分かりにくかったので`time_formats.rb` を追加しました。
これで何も意識しなくても %Y年%m月%d日 %H:%M で表示されるはずです。

EventをCRUDできるようにした

---

app/controllers/admin/personalities_controller.rb
app/views/layouts/admin.html.erb

closed #21 
csrf-meta-tagを追加しました。

csrf-mera-tagを入れ忘れていたので追加

---

app/controllers/admin/communities_controller.rb
app/helpers/admin/communities_helper.rb
app/models/community.rb
app/views/admin/communities/_form.html.erb
app/views/admin/communities/edit.html.erb
app/views/admin/communities/index.html.erb
app/views/admin/communities/new.html.erb
app/views/admin/communities/show.html.erb
app/views/layouts/admin.html.erb
config/locales/models/community.ja.yml
config/routes.rb
db/fixtures/20_community.rb
db/migrate/20171114145623_create_communities.rb
db/schema.rb
spec/factories/communities.rb
spec/models/community_spec.rb

コミュニティをCRUDできるようにした

---

app/controllers/admin/radios_controller.rb
app/models/radio.rb
app/views/admin/radios/_form.html.erb
app/views/admin/radios/show.html.erb
config/locales/models/radio.ja.yml
db/fixtures/40_radio.rb
db/migrate/20171118125737_add_columns_to_radios.rb
db/schema.rb

ラジオにcolumnを追加した

---

app/controllers/admin/radios_controller.rb
app/models/community.rb
app/models/community_radio.rb
app/models/radio.rb
app/views/admin/communities/show.html.erb
app/views/admin/radios/_form.html.erb
app/views/admin/radios/show.html.erb
config/locales/models/community.ja.yml
config/locales/models/radio.ja.yml
db/fixtures/30_event.rb
db/fixtures/40_radio.rb
db/migrate/20171118141009_create_community_radios.rb
db/schema.rb
spec/factories/community_radios.rb
spec/models/community_radio_spec.rb

コミュニティとラジオの多対多の実装

---

app/controllers/admin/radios_controller.rb
app/models/personality.rb
app/models/radio.rb
app/models/radio_personality.rb
app/views/admin/personalities/show.html.erb
app/views/admin/radios/_form.html.erb
app/views/admin/radios/show.html.erb
config/locales/models/personality.ja.yml
config/locales/models/radio.ja.yml
config/unicorn/production.rb
db/fixtures/40_radio.rb
db/migrate/20171118150337_create_radio_personalities.rb
db/schema.rb
spec/factories/radio_personalities.rb
spec/models/radio_personality_spec.rb

ラジオとパーソナリティの多対多を実装した

---

config/deploy.rb

deploy時にslackに通知されるようにした

---

app/views/devise/passwords/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/layouts/devise.html.erb
config/application.rb
config/locales/models/personality.ja.yml

ログイン画面をカッコよくした

---

Gemfile
Gemfile.lock
app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/communities_controller.rb
app/controllers/api/v1/events_controller.rb
app/controllers/api/v1/personalities_controller.rb
app/controllers/api/v1/radios_controller.rb
app/serializers/community_serializer.rb
app/serializers/event_serializer.rb
app/serializers/personality_serializer.rb
app/serializers/radio_serializer.rb
config/routes.rb
lib/tasks/auto_annotate_models.rake

closed #66 
生成したrouting
* /api/v1/communities
* /api/v1/communities/1
* /api/v1/events
* /api/v1/events/1
* /api/v1/personalities
* /api/v1/personalities/1
* /api/v1/radios
* /api/v1/radios/1
とりあえず基本的なものを作ってみました。

基本的なAPIを作成

---

app/controllers/api/v1/events_controller.rb
app/controllers/api/v1/personalities_controller.rb
app/controllers/api/v1/radios_controller.rb

`Api::V1::BaseController` を継承し忘れていました。。。

bese_controllerを継承するよう修正

---

app/services/podcast/feed.rb

rssへmarkdownでの変更を反映しきれてませんでした。

podcastできちんとしたhtmlでdescriptionが表示されるよう修正

---

public/css/common.css
public/index.html
public/policy.html

「プライバシーポリシー」の静的ページを作成する

---

public/index.html

closed #87 
@chanyou0311 @euglena1215  
参考
https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

メインのコンテンツが短すぎたときのフッターを修正

---

public/member_detail.html
public/member_list.html

パーソナリティ関係のページの静的ページを作成する

---

frontend/src/components/header.vue
frontend/src/pages/top.vue

メニューを機能させる

---

app/enums/personality_roles.rb
app/models/personality.rb
config/locales/enums/personality_roles.ja.yml

データを操作したいけど、パーソナリティに表示させられないという人がいるというのを聞いたので
roleにSERCETを追加した。
特になし。

add role secret

---

app/helpers/markdown_helper.rb
app/serializers/personality_serializer.rb

closed #141 
issueに書いてあるバグを修正しました。
特になし。

自己紹介が入力されていないパーソナリティを表示させようとしたときに落ちる問題を修正した

---

app/controllers/admin/devise/sessions_controller.rb
app/views/layouts/_sidebar.html.erb
app/views/layouts/admin.html.erb
config/routes.rb

closed #6 
* ログアウトできるようにした
* ログインしている人の名前と権限を表示
* sidebarをpartialに切り分けた
* スマホ対応

ログアウト機能の追加

---

app/services/podcast/config.rb
app/services/podcast/feed.rb

closed #114 
* 今のサイトでpodcast配信をしたときにblubrryで統計データを取得できるようにしました。
rssのmp3のsrcがlocalだと `/uploads/radios/mp3/1.mp3` みたいになってたのを `http://localhost:5000/uploads/radios/mp3/1.mp3` とURLになるように変更しました。
特になし。

add settting blubrry

---

app/services/podcast/feed.rb

`transform_to_blubrry` がバグってました。
すみませんm(_ _)m
特になし。

bug fix `transform_to_blubrry`

---

app/services/podcast/config.rb
app/services/podcast/feed.rb

【2017/12/30】リリース

---

app/controllers/admin/devise/passwords_controller.rb
app/views/devise/passwords/edit.html.erb
config/environments/development.rb
config/routes.rb

closed #140 
* パスワード変更の見た目を修正しました。
* パスワード変更した後 `admin/` に遷移するようにしました。
* letter_openerのポートを5000に変更しました。
特になし。

change password form

---

app/controllers/admin/communities_controller.rb
app/controllers/admin/events_controller.rb
app/controllers/admin/jargons_controller.rb
app/controllers/admin/personalities_controller.rb
app/controllers/admin/radios_controller.rb
app/views/admin/communities/index.html.erb
app/views/admin/communities/show.html.erb
app/views/admin/events/index.html.erb
app/views/admin/events/show.html.erb
app/views/admin/jargons/index.html.erb
app/views/admin/jargons/show.html.erb
app/views/admin/personalities/index.html.erb
app/views/admin/personalities/show.html.erb
app/views/admin/radios/index.html.erb
app/views/admin/radios/show.html.erb
app/views/layouts/admin.html.erb

* 散らばっていたnoticeをまとめた
* noticeに `alert-info` をつけた
* noticeの文言を日本語にした。
特になし。

noticeをいい感じにした

---

app/controllers/admin/radios_controller.rb
app/models/radio.rb
app/serializers/radio_serializer.rb
app/uploaders/radio_digest_mp3_uploader.rb
app/views/admin/radios/_form.html.erb
app/views/admin/radios/show.html.erb
config/locales/models/radio.ja.yml
db/migrate/20180115154351_add_digest_mp3_to_radios.rb
db/schema.rb
frontend/src/components/radio-preview.vue
frontend/src/pages/top.vue

ダイジェスト版を聞けるようにした

---

frontend/src/packs/root.js

closed #132
- 遷移時に画面上部にスクロールさせる

遷移時に画面上部にスクロールさせる

---

frontend/src/packs/root.js

- IEで表示されないバグの修正
- こんなことしなくてもBabelとかでいいかんじにしてくれるのがあると思うけどできてない

とりあえずのIE対応

---

frontend/src/pages/radio.vue

シェアボタンの位置の修正

---

config/unicorn/production.rb
config/unicorn/staging.rb

unicornのタイムアウトを30秒から300秒に伸ばしました
300秒が正しいのかはわからない

unicornのtimeoutを伸ばした

---

middleware/nginx/production.conf
middleware/nginx/staging.conf

nginxがgitの管理外にあるため履歴が残せない。
middleware/nginxにconfを入れるようにしました。
現状はシンボリックリンクはまだ貼ってないのでconfファイルがただ置いてあるだけの状態です。
マージされ次第シンボリックリンクを貼ります。

Including nginx conf

---

.circleci/config.yml

- テストが通らなくなったから
- .circleci/config.yml でバージョン指定した

Appoint mysql version

---

frontend/src/components/RadioHistoryContentWrapper.tsx
frontend/src/components/RadioSeacher.tsx
frontend/src/entries/RadioHistory.tsx
frontend/src/layouts/Header.tsx
frontend/src/layouts/Main.tsx

Create Radio History Wireframe

---

app/helpers/application_helper.rb
frontend/package.json
frontend/webpack.config.js
frontend/yarn.lock

- デザインリニューアルに伴い、編集後毎回リロードするのはめんどくさいから

webpack-dev-serverを導入して、hot reloadできるようにした

---

frontend/package.json
frontend/src/components/TweetStream.tsx
frontend/yarn.lock

closed #289 
TweetStreamコンポーネントを表示させるため
- とりあえずでちょっくれアカウントのツイートを埋め込みました

Add TweetStream
